name: Check Update

on:
  schedule:
    - cron: "4 * * * *"
  workflow_dispatch:
    inputs:
      desc:
        description: "desc"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Run update script
        run: ./update.sh
        shell: bash
